# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
    level:
        ROOT: DEBUG
        io.github.jhipster: DEBUG
        com.vodworks: DEBUG

eureka:
    instance:
        prefer-ip-address: true
    client:
        enabled: false # By default, the JHipster Registry is not used in the "dev" profile
        service-url:
            defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/

spring:
    profiles:
        active: dev
        include:
        - swagger
        # Uncomment to activate TLS for the dev profile
        #- tls
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use Webpack dev server + BrowserSync for livereload
    jackson:
        serialization:
            indent-output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/ce_igmock_jhipster?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: root
        hikari:
            poolName: Hikari
            auto-commit: false
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.connection.provider_disables_autocommit: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
    liquibase:
        # Remove 'faker' if you do not want the sample data to be loaded automatically
        contexts: dev, faker
    mail:
        host: localhost
        port: 25
        username:
        password:
    messages:
        cache-duration: PT1S # 1 second, see the ISO 8601 standard
    thymeleaf:
        cache: false
    sleuth:
        sampler:
            probability: 1 # report 100% of traces
    zipkin: # Use the "zipkin" Maven profile to have the Spring Cloud Zipkin dependencies
        base-url: http://localhost:9411
        enabled: false
        locator:
            discovery:
                enabled: true

server:
    port: 8080

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
    # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
    cors:
        allowed-origins: '*'
        allowed-methods: '*'
        allowed-headers: '*'
        exposed-headers: 'Authorization,Link,X-Total-Count'
        allow-credentials: true
        max-age: 1800
    security:
        authentication:
            jwt:
                # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
                base64-secret: Nzk3NDhkZTYwODVkZjk0NmVjZWM0ZGE0YmI2NmUzYzRmN2RhN2U4NGM3NzM2OWFmMmU1YmQ4YmI5MzE1MTMzZWFhZjZjZWVjMWZmMTBjMmZjYmUyNGViODJjZTY3MzFjZjQ3ZjI5ODQwZjQ0OTQ2OWVmZjdhNDVjNmVhMjg4MTg=
                # Token is valid 24 hours
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: jhipster_demo_app@localhost
        base-url: http://127.0.0.1:8080
    metrics:
        logs: # Reports metrics in the logs
            enabled: false
            report-frequency: 60 # in seconds
    logging:
        use-json-format: false # By default, logs are not in Json format
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queue-size: 512
            # ===================================================================
            # Application specific properties
            # Add your own application properties here, see the ApplicationProperties class
            # to have type-safe configuration, like in the JHipsterProperties above
            #
            # More documentation is available at:
            # https://www.jhipster.tech/common-application-properties/
            # ===================================================================

    #application:
#    question:
#        rate-identify: {"type":"rate-identify","title":"","statement":"I identify as:","leftEnd":{"type":"text","label":"<LEFT_LABEL>","valueNumber":0},"rightEnd":{"type":"text","label":"<RIGHT_LABEL>","valueNumber":100}}
#        text-thinkof: {"type":"text-thinkof","title":"Brand Questions","statement":"When you think of <BRAND_CATEGORY>, what brands have you heard of?","textLimit":1000}
#        brands-heard-of: {"type":"brands-heard-of","title":"Brand Questions","statement":"Which of these brands have you heard of?","questions":[{"id":0,"controlType":"image-selection","valueString":"<BRAND_NAME>","label":"<BRAND_LOGO_URL>"},{"id":1,"controlType":"image-selection","valueString":"<COMPETITOR_1_NAME>","label":"<COMPETITOR_1_LOGO_URL>"},{"id":2,"controlType":"image-selection","valueString":"<COMPETITOR_2_NAME>","label":"<COMPETITOR_2_LOGO_URL>"}]}
#        rate-opinion: {"type":"rate-opinion","title":"Brand Questions","statement":"What is your opinion of these brands? (1 - negative, 10 - positive)","statementImageUrl":"<COMPETITOR_LOGO_URL>"}
#        rate-purchase: {"type":"rate-purchase","title":"Brand Questions","statement":"How likely would you be to purchase the following <BRAND_CATEGORY> products, in the next 3  months?","statementImageUrl":"<COMPETITOR_LOGO_URL>","leftEnd":{"type":"text","label":"Very unlikely","valueNumber":0},"rightEnd":{"type":"text","label":"Very likely","valueNumber":100}}
#        yes-no: {"type":"yes-no","title":"","statement":"<BRAND_TRAIT>","option":{"type":"imgUrl","valueString":"yes/no","label":"<COMPETITOR_LOGO_URL>"}}
#        rate-creative: {"type":"rate-creative","title":"Creative Questions","statement":"<CREATIVE_QUESTION_STATEMENT>","leftEnd":{"type":"text","label":"Very unlikely","valueNumber":0},"rightEnd":{"type":"text","label":"Very likely","valueNumber":100}}
#        text-remember: {"type":"text-remember","title":"Creative Questions","statement":"Which brands did you see in the post?","textLimit":1000,"answerOptions":[{"type":"text","valueString":"I can't remember","label":"I can't remember"},{"type":"text","valueString":"I couldn't tell","label":"I couldn't tell"},{"type":"text","valueString":"There was no brand","label":"There was no brand"}]}
#        rate-purchase-again: {"type":"rate-purchase-again","title":"Brand Questions","statement":"How likely would you be to continue purchasing the following brands time and again?","questions":[{"id":0,"controlType":"image-slider","statementImageUrl":"<BRAND_LOGO_URL>","leftEnd":{"type":"text","label":"Very unlikely","valueNumber":0},"rightEnd":{"type":"text","label":"Very likely","valueNumber":100}},{"id":1,"controlType":"image-slider","statementImageUrl":"<COMPETITOR_1_LOGO_URL>","leftEnd":{"type":"text","label":"Very unlikely","valueNumber":0},"rightEnd":{"type":"text","label":"Very likely","valueNumber":100}},{"id":2,"controlType":"image-slider","statementImageUrl":"<COMPETITOR_2_LOGO_URL>","leftEnd":{"type":"text","label":"Very unlikely","valueNumber":0},"rightEnd":{"type":"text","label":"Very likely","valueNumber":100}}]}
#        rate-recommend: {"type":"rate-recommend","title":"Brand Questions","statement":"How likely would you be to recommend the following brands to friends and family?","questions":[{"id":0,"controlType":"image-slider","statementImageUrl":"<BRAND_LOGO_URL>","leftEnd":{"type":"text","label":"Very unlikely","valueNumber":0},"rightEnd":{"type":"text","label":"Very likely","valueNumber":100}},{"id":1,"controlType":"image-slider","statementImageUrl":"<COMPETITOR_1_LOGO_URL>","leftEnd":{"type":"text","label":"Very unlikely","valueNumber":0},"rightEnd":{"type":"text","label":"Very likely","valueNumber":100}},{"id":2,"controlType":"image-slider","statementImageUrl":"<COMPETITOR_2_LOGO_URL>","leftEnd":{"type":"text","label":"Very unlikely","valueNumber":0},"rightEnd":{"type":"text","label":"Very likely","valueNumber":100}}]}
#        rate-influencer: {"type":"rate-influencer","title":"Influencer Questions","statement":"To what extent did the influencer fit the brand in the post?","controlType":"text-slider","leftEnd":{"type":"text","label":"Not at all","valueNumber":0},"rightEnd":{"type":"text","label":"A great deal","valueNumber":100}}
#        sub-influencer: {"type":"sub-influencer","title":"Influencer Questions","statement":"To what extent do you think the influencer is:","questions":[{"id":0,"controlType":"text-slider","statement":"Genuine?","leftEnd":{"type":"text","label":"Not at all","valueNumber":0},"rightEnd":{"type":"text","label":"A great deal","valueNumber":100}},{"id":1,"controlType":"text-slider","statement":"Relevant to you?","leftEnd":{"type":"text","label":"Not at all","valueNumber":0},"rightEnd":{"type":"text","label":"A great deal","valueNumber":100}},{"id":2,"controlType":"text-slider","statement":"Credible?","leftEnd":{"type":"text","label":"Not at all","valueNumber":0},"rightEnd":{"type":"text","label":"A great deal","valueNumber":100}},{"id":3,"controlType":"text-slider","statement":"Cool?","leftEnd":{"type":"text","label":"Not at all","valueNumber":0},"rightEnd":{"type":"text","label":"A great deal","valueNumber":100}},{"id":4,"controlType":"text-slider","statement":"Relatable?","leftEnd":{"type":"text","label":"Not at all","valueNumber":0},"rightEnd":{"type":"text","label":"A great deal","valueNumber":100}},{"id":5,"controlType":"text-slider","statement":"Original?","leftEnd":{"type":"text","label":"Not at all","valueNumber":0},"rightEnd":{"type":"text","label":"A great deal","valueNumber":100}},{"id":6,"controlType":"text-slider","statement":"Innovative?","leftEnd":{"type":"text","label":"Not at all","valueNumber":0},"rightEnd":{"type":"text","label":"A great deal","valueNumber":100}},{"id":7,"controlType":"text-slider","statement":"Empowering?","leftEnd":{"type":"text","label":"Not at all","valueNumber":0},"rightEnd":{"type":"text","label":"A great deal","valueNumber":100}},{"id":8,"controlType":"text-slider","statement":"Trustworthy?","leftEnd":{"type":"text","label":"Not at all","valueNumber":0},"rightEnd":{"type":"text","label":"A great deal","valueNumber":100}}]}
#        sub-likely: {"type":"sub-likely","title":"Influencer Questions","statement":"How likely are you to:","questions":[{"id":0,"controlType":"text-slider","statement":"Recommend the influencer to your friends or family?","leftEnd":{"type":"text","label":"Very unlikely","valueNumber":0},"rightEnd":{"type":"text","label":"Very likely","valueNumber":100}},{"id":1,"controlType":"text-slider","statement":"Be inspired by the influencer?","leftEnd":{"type":"text","label":"Very unlikely","valueNumber":0},"rightEnd":{"type":"text","label":"Very likely","valueNumber":100}},{"id":2,"controlType":"text-slider","statement":"Purchase the products promoted by the influencer?","leftEnd":{"type":"text","label":"Very unlikely","valueNumber":0},"rightEnd":{"type":"text","label":"Very likely","valueNumber":100}}]}
#        sub-grid-creative-emotion: {"type":"sub-grid-creative-emotion","title":"Creative Questions","statement":"What emotions did you feel while viewing this post?","subStatement":"For the emotions you have selected, how intensely did you feel them?","questions":[{"id":0,"controlType":"text-slider","statement":"Sympathy","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":1,"controlType":"text-slider","statement":"Satisfaction","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":2,"controlType":"text-slider","statement":"Admiration","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":3,"controlType":"text-slider","statement":"Excitement","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":4,"controlType":"text-slider","statement":"Triumph","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":5,"controlType":"text-slider","statement":"Warmth","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":6,"controlType":"text-slider","statement":"Nostalgia","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":7,"controlType":"text-slider","statement":"Awe","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":8,"controlType":"text-slider","statement":"Amusement","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":9,"controlType":"text-slider","statement":"Romance","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":10,"controlType":"text-slider","statement":"Interest","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":11,"controlType":"text-slider","statement":"Calmness","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":12,"controlType":"text-slider","statement":"Sexual desire","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":13,"controlType":"text-slider","statement":"Aesthetic appreciation","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":14,"controlType":"text-slider","statement":"Inspiration","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":15,"controlType":"text-slider","statement":"Joy","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":16,"controlType":"text-slider","statement":"Adoration","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":17,"controlType":"text-slider","statement":"Entrancement","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":18,"controlType":"text-slider","statement":"Horror","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":19,"controlType":"text-slider","statement":"Disgust","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":20,"controlType":"text-slider","statement":"Fear","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":21,"controlType":"text-slider","statement":"Confusion","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":22,"controlType":"text-slider","statement":"Sadness","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":23,"controlType":"text-slider","statement":"Craving","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":24,"controlType":"text-slider","statement":"Anxiety","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":25,"controlType":"text-slider","statement":"Envy","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":26,"controlType":"text-slider","statement":"Empathetic pain","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":27,"controlType":"text-slider","statement":"Awkwardness","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":28,"controlType":"text-slider","statement":"Boredom","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}},{"id":29,"controlType":"text-slider","statement":"Contempt","leftEnd":{"type":"text","label":"Not very strongly","valueNumber":0},"rightEnd":{"type":"text","label":"Extremely strongly","valueNumber":100}}]}
#        rate-identify.parameters: Cautious:Open,Spontaneous:Conscientious,Introverted:Extroverted,Challenging:Cooperative,Calm:Passionate
#        rate-creative.parameters: Find out more about the product in the post?,Purchase the product in the post?,Share this post on social media?
